### PR TITLE
fix(bundle): ENTESB-15469 - hide spec.rbac.enabled from CRD schema

### PR DESCRIPTION
**Pull request by tadayosi**
https://issues.redhat.com/browse/ENTESB-15469

Followed Antonin's suggestion https://github.com/hawtio/hawtio-operator/pull/46#issuecomment-763468116

### CODE REVIEW

**Comment by astefanutti** [comment]
@tadayosi, thanks. Should we also remove the field from the API altogether, as the CRD resources are code-generated:

https://github.com/hawtio/hawtio-operator/blob/671828d6cf316a8e4fb0914edfb8c49da726417d/pkg/apis/hawtio/v1alpha1/hawtio_types.go#L81

As a side node, this is somewhat breaking compatibility, though I don't think it is used. If that would be the use, I think it is acceptable to suggest manual patching of the Hawtio resource.

**Comment by tadayosi** [comment]
Hmm, I haven't removed it from the type API because I also think it's a bit big change that breaks compatibility. To me it seems to be a bit too much for this small issue at ENTESB-15469. That way, I thought it's not explicit to users but they can still apply `spec.rbac.enabled: false` to disable the feature for the time being.

**Comment by astefanutti** [comment]
I think removing it from the CRD already breaks compatibility, as the CR won't validate. The difference between removing the field, is that users would still be able to disable RBAC by using the `kubectl create --force` option to bypass validation. That may be also an acceptable tradeoff. That being said, I'd be inclined to take that opportunity to remove an option that increase configurability and testing cost, the rational being that there is no value to deactivate RBAC. WDYT?

**Comment by tadayosi** [comment]
For `apiextensions.k8s.io/v1beta`, `spec.preserveUnknownFields` appears to be `true` by default so any fields that are not known in the schema just get accepted:
https://kubernetes.io/blog/2019/06/20/crd-structural-schema/#pruning-don-t-preserve-unknown-fields
https://kubernetes.io/docs/tasks/extend-kubernetes/custom-resources/custom-resource-definitions/#field-pruning

I tried the following addtion to `deploy/crs/hawtio_v1alpha1_hawtio_cr.yaml`:
```
     requests:
       cpu: 200m
       memory: 32Mi
+  rbac:
+    enabled: false
```
and ran `kubectl create -f deploy/crs/hawtio_v1alpha1_hawtio_cr.yaml` successfully.

That said, I'm now convinced that we take this opportunity to prune the unneeded option. I'll follow up with a subsequent commit soon.

**Review by astefanutti — APPROVED** [review]

**Pull request merged**
